import articoloApi from '../api/articoloApi';
import clienteApi from '../api/clienteApi';
import contatoreApi from '../api/contatoreApi';
import edificioApi from '../api/edificioApi';
import fasciaApi from '../api/fasciaApi';
import fatturaApi from '../api/fatturaApi';
import letturaApi from '../api/letturaApi';
import listinoApi from '../api/listinoApi';
import scadenzaApi from '../api/scadenzaApi';
import servizioApi from '../api/servizioApi';
import ArticoloEditor from '../components/shared/ArticoloEditor';
import ClienteEditor from '../components/shared/ClienteEditor';
import ContatoreEditor from '../components/shared/ContatoreEditor';
import EdificioEditor from '../components/shared/EdificioEditor';
import FasciaEditor from '../components/shared/FasciaEditor';
import FatturaEditor from '../components/shared/FatturaEditor';
import LetturaEditor from '../components/shared/LetturaEditor';
import ListinoEditor from '../components/shared/ListinoEditor';
import ScadenzaEditor from '../components/shared/ScadenzaEditor';
import ServizioEditor from '../components/shared/ServizioEditor';
import {
    boolText,
    formatDate,
    formatMoney,
    fullName,
    join,
    text,
} from '../utils/formatters';

const api = (get, update, remove) => ({ get, update, remove });

export const detailViews = {
    articoli: {
        resource: 'articoli',
        listPath: '/articoli',
        title: 'Dettagli Articolo',
        editorProp: 'articolo',
        EditorComponent: ArticoloEditor,
        api: api(articoloApi.getArticolo, articoloApi.updateArticolo, articoloApi.deleteArticolo),
        relations: ['servizi'],
        fields: [
            { label: 'Codice', value: 'codice' },
            { label: 'Descrizione', value: 'descrizione' },
            { label: 'IVA', value: 'iva' },
        ],
    },
    clienti: {
        resource: 'clienti',
        listPath: '/clienti',
        title: 'Dettagli Cliente',
        editorProp: 'cliente',
        EditorComponent: ClienteEditor,
        api: api(clienteApi.getCliente, clienteApi.updateCliente, clienteApi.deleteCliente),
        relations: ['contatori', 'fatture'],
        fields: [
            { label: 'Ragione Sociale', value: 'ragione_sociale' },
            { label: 'Cognome', value: 'cognome' },
            { label: 'Nome', value: 'nome' },
            { label: 'Sesso', value: 'sesso' },
            { label: 'Socio', value: 'socio', format: boolText },
            { label: 'Quote', value: 'quote' },
            { label: 'Commerciali', value: 'con_commerciali' },
            { label: 'Data di Nascita', value: 'data_nascita', format: formatDate },
            { label: 'Comune di Nascita', value: 'comune_nascita' },
            { label: 'Provincia di Nascita', value: 'provincia_nascita' },
            { label: 'Indirizzo di Residenza', value: (record) => join(record.indirizzo_residenza, record.numero_residenza) },
            { label: 'CAP di Residenza', value: 'cap_residenza' },
            { label: 'Localita di Residenza', value: 'localita_residenza' },
            { label: 'Provincia di Residenza', value: 'provincia_residenza' },
            { label: 'Nazione di Residenza', value: 'nazione_residenza' },
            { label: 'Destinazione di Fatturazione', value: 'destinazione_fatturazione' },
            { label: 'Indirizzo di Fatturazione', value: (record) => join(record.indirizzo_fatturazione, record.numero_fatturazione) },
            { label: 'CAP di Fatturazione', value: 'cap_fatturazione' },
            { label: 'Localita di Fatturazione', value: 'localita_fatturazione' },
            { label: 'Provincia di Fatturazione', value: 'provincia_fatturazione' },
            { label: 'Nazione di Fatturazione', value: 'nazione_fatturazione' },
            { label: 'Codice Fiscale', value: 'codice_fiscale' },
            { label: 'Partita IVA', value: 'partita_iva' },
            { label: 'Stampa di cortesia', value: 'stampa_cortesia' },
            { label: 'Telefono', value: 'telefono' },
            { label: 'Cellulare', value: 'cellulare' },
            { label: 'Cellulare 2', value: 'cellulare2' },
            { label: 'Email', value: 'email' },
            { label: 'Pagamento', value: 'pagamento' },
            { label: 'Data Mandato SDD', value: 'data_mandato_sdd', format: formatDate },
            { label: 'Email PEC', value: 'email_pec' },
            { label: 'Codice Destinatario', value: 'codice_destinatario' },
            { label: 'Fattura Elettronica', value: 'fattura_elettronica', format: boolText },
            { label: 'Codice ERP', value: 'codice_cliente_erp' },
            { label: 'IBAN', value: 'iban' },
            { label: 'Note', value: 'note' },
        ],
    },
    contatori: {
        resource: 'contatori',
        listPath: '/contatori',
        title: 'Dettagli Contatore',
        editorProp: 'contatore',
        EditorComponent: ContatoreEditor,
        api: api(contatoreApi.getContatore, contatoreApi.updateContatore, contatoreApi.deleteContatore),
        relations: ['cliente', 'letture', 'edificio', 'listino'],
        fields: [
            { label: 'Tipo Contatore', value: 'tipo_contatore' },
            { label: 'Codice', value: 'codice' },
            { label: 'Nome Cliente', value: 'nome_cliente' },
            { label: 'Seriale Interno', value: 'seriale_interno' },
            { label: 'Nome Edificio', value: 'nome_edificio' },
            { label: 'Tipo Attivita', value: 'tipo_attivita' },
            { label: 'Seriale', value: 'seriale' },
            { label: 'Inattivo', value: 'inattivo', format: boolText },
            { label: 'Consumo', value: 'consumo' },
            { label: 'Subentro', value: 'subentro', format: boolText },
            { label: 'Sostituzione', value: 'sostituzione', format: boolText },
            { label: 'Condominiale', value: 'condominiale', format: boolText },
            { label: 'Inizio', value: 'inizio', format: formatDate },
            { label: 'Scadenza', value: 'scadenza', format: formatDate },
            { label: 'Causale', value: 'causale' },
            { label: 'Note', value: 'note' },
            { label: 'Foto', value: 'foto' },
            { label: 'Listino', value: 'listino.descrizione' },
            { label: 'Cliente', value: (record) => record.cliente ? fullName(record.cliente) : '' },
            { label: 'Edificio', value: 'edificio.descrizione' },
        ],
    },
    edifici: {
        resource: 'edifici',
        listPath: '/edifici',
        title: 'Dettagli Edificio',
        editorProp: 'edificio',
        EditorComponent: EdificioEditor,
        api: api(edificioApi.getEdificio, edificioApi.updateEdificio, edificioApi.deleteEdificio),
        relations: ['contatori'],
        fields: [
            { label: 'Descrizione', value: 'descrizione' },
            { label: 'Indirizzo', value: (record) => join(record.indirizzo, record.numero) },
            { label: 'CAP', value: 'cap' },
            { label: 'Localita', value: 'localita' },
            { label: 'Provincia', value: 'provincia' },
            { label: 'Nazione', value: 'nazione' },
            { label: 'Attivita', value: 'attivita' },
            { label: 'Posti letto', value: 'posti_letto' },
            { label: 'Latitudine', value: 'latitudine' },
            { label: 'Longitudine', value: 'longitudine' },
            { label: 'Unita abitative', value: 'unita_abitative' },
            { label: 'Catasto', value: 'catasto' },
            { label: 'Foglio', value: 'foglio' },
            { label: 'PED', value: 'ped' },
            { label: 'Estensione', value: 'estensione' },
            { label: 'Tipo', value: 'tipo' },
            { label: 'Note', value: 'note' },
        ],
    },
    fasce: {
        resource: 'fasce',
        listPath: '/fasce',
        title: 'Dettagli Fascia',
        editorProp: 'fascia',
        EditorComponent: FasciaEditor,
        api: api(fasciaApi.getFascia, fasciaApi.updateFascia, fasciaApi.deleteFascia),
        relations: ['listino'],
        fields: [
            { label: 'Tipo', value: 'tipo' },
            { label: 'Minimo', value: 'min' },
            { label: 'Massimo', value: 'max' },
            { label: 'Prezzo', value: 'prezzo', format: formatMoney },
            { label: 'Inizio', value: 'inizio', format: formatDate },
            { label: 'Scadenza', value: 'scadenza', format: formatDate },
        ],
    },
    fatture: {
        resource: 'fatture',
        listPath: '/fatture',
        title: 'Dettagli Fattura',
        editorProp: 'fattura',
        EditorComponent: FatturaEditor,
        api: api(fatturaApi.getFattura, fatturaApi.updateFattura, fatturaApi.deleteFattura),
        relations: ['cliente', 'servizi', 'scadenza'],
        fields: [
            { label: 'Tipo Documento', value: 'tipo_documento' },
            { label: 'Ragione Sociale', value: 'ragione_sociale' },
            { label: 'Confermata', value: 'confermata', format: boolText },
            { label: 'Anno', value: 'anno' },
            { label: 'Numero', value: 'numero' },
            { label: 'Data Fattura', value: 'data_fattura', format: formatDate },
            { label: 'Codice', value: 'codice' },
            { label: 'Destinazione', value: 'destinazione' },
            { label: 'Imponibile', value: 'imponibile', format: formatMoney },
            { label: 'IVA', value: 'iva', format: formatMoney },
            { label: 'Sconto imponibile', value: 'sconto_imponibile', format: formatMoney },
            { label: 'Totale fattura', value: 'totale_fattura', format: formatMoney },
            { label: 'Data fattura elettronica', value: 'data_fattura_elettronica', format: formatDate },
            { label: 'Data invio fattura', value: 'data_invio_fattura', format: formatDate },
            { label: 'Tipo pagamento', value: 'tipo_pagamento' },
            { label: 'Cliente', value: (record) => record.cliente ? fullName(record.cliente) : '' },
        ],
    },
    letture: {
        resource: 'letture',
        listPath: '/letture',
        title: 'Dettagli Lettura',
        editorProp: 'lettura',
        EditorComponent: LetturaEditor,
        api: api(letturaApi.getLettura, letturaApi.updateLettura, letturaApi.deleteLettura),
        relations: ['servizi', 'contatore'],
        fields: [
            { label: 'Data Lettura', value: 'data_lettura', format: formatDate },
            { label: 'Consumo', value: (record) => join(record.consumo, record.unita_misura) },
            { label: 'Fatturata', value: 'fatturata', format: boolText },
            { label: 'Tipo', value: 'tipo' },
            { label: 'Note', value: 'note' },
            { label: 'Contatore', value: (record) => text(record.contatore?.seriale) },
        ],
    },
    listini: {
        resource: 'listini',
        listPath: '/listini',
        title: 'Dettagli Listino',
        editorProp: 'listino',
        EditorComponent: ListinoEditor,
        api: api(listinoApi.getListino, listinoApi.updateListino, listinoApi.deleteListino),
        relations: ['fasce', 'contatori'],
        fields: [
            { label: 'Categoria', value: 'categoria' },
            { label: 'Descrizione', value: 'descrizione' },
        ],
    },
    scadenze: {
        resource: 'scadenze',
        listPath: '/scadenze',
        title: 'Dettagli Scadenza',
        editorProp: 'scadenza',
        EditorComponent: ScadenzaEditor,
        api: api(scadenzaApi.getScadenza, scadenzaApi.updateScadenza, scadenzaApi.deleteScadenza),
        relations: ['fattura'],
        fields: [
            { label: 'Scadenza', value: 'scadenza', format: formatDate },
            { label: 'Saldo', value: 'saldo', format: boolText },
            { label: 'Pagamento', value: 'pagamento', format: formatDate },
            { label: 'Ritardo', value: (record) => (
                record.ritardo === undefined || record.ritardo === null || record.ritardo === ''
                    ? ''
                    : `${record.ritardo} giorni`
            ) },
            { label: 'Anno', value: 'anno' },
            { label: 'Numero', value: 'numero' },
            { label: 'Cognome', value: 'cognome' },
            { label: 'Nome', value: 'nome' },
            { label: 'Totale', value: 'totale', format: formatMoney },
            { label: 'Solleciti', value: 'solleciti' },
        ],
    },
    servizi: {
        resource: 'servizi',
        listPath: '/servizi',
        title: 'Dettagli Servizio',
        editorProp: 'servizio',
        EditorComponent: ServizioEditor,
        api: api(servizioApi.getServizio, servizioApi.updateServizio, servizioApi.deleteServizio),
        relations: ['lettura', 'articolo', 'fattura'],
        fields: [
            { label: 'Descrizione', value: 'descrizione' },
            { label: 'Tariffa', value: 'tipo_tariffa' },
            { label: 'Tipo attivita', value: 'tipo_attivita' },
            { label: 'Metri cubi', value: 'metri_cubi' },
            { label: 'Prezzo', value: 'prezzo', format: formatMoney },
            { label: 'Valore unitario', value: 'valore_unitario', format: formatMoney },
            { label: 'Tipo quota', value: 'tipo_quota' },
            { label: 'Seriale condominio', value: 'seriale_condominio' },
            { label: 'Lettura precedente', value: 'lettura_precedente' },
            { label: 'Lettura fatturazione', value: 'lettura_fatturazione' },
            { label: 'Data Lettura', value: 'data_lettura', format: formatDate },
            { label: 'Descrizione attivita', value: 'descrizione_attivita' },
        ],
    },
};
